### PR TITLE
Powers of two multiples gadget implemented for Twisted Edwards Curves

### LINKED ISSUE #35: Implement $2^{i}G$  gadget
The gadget deals with an columns made of $(2^{i}G)$ vector and enforcing $G_{i+1}=2G_{i}$ later it could be used by cond_add to enforce the equality of public key to $sk G$.
  see https://hackmd.io/@CmbtIje1Sxq-KCOjcxDmbQ/rkquceVCR/edit for more details.

### PR DESCRIPTION
**Pull request by drskalman**
Closes #35

### CODE REVIEW

**Comment by davxy** [comment]
Is this identical to https://github.com/davxy/ring-proof/pull/5? If so, I propose moving forward with it, integrating it quickly so it can be used in JAM, and then submitting a PR here from my fork. I say so just to work twice to keep keep the PRs in sync.

**Comment by drskalman** [comment]
> @drskalman Is this identical to [davxy#5](https://github.com/davxy/ring-proof/pull/5)?

Basically, I just made the mistake of pushing https://github.com/w3f/ring-proof/pull/36/commits/7a1f3ff7d8589083fd71495e90b853cb9e78e9b5 to your branch, which I didn't mean to. But i don't see any harm in including an extra gadgedt in your fork. It is going to be used in verifying VRF in the SNARK for Verifiable.

**Comment by swasilyev** [comment]
Ok, i finally noticed it

**Review by davxy — CHANGES_REQUESTED** [review]
Blocker: https://github.com/w3f/ring-proof/pull/39

**Review by davxy — APPROVED** [review]
LGTM

**Comment by davxy** [comment]
@drskalman @swasilyev is there any blocker?

**Comment by swasilyev** [comment]
Please repeat wo reformatting all the code. Also there s no need in a trait for te/sw gadgets. The circuit knows in which form the data is.

**Comment by swasilyev** [comment]
Or first reformat, add the formatting rules to the ci, the send the pr

**Comment by swasilyev** [comment]
Still not adequate for review. The traits have to be removed.

**Pull request closed without merging**
