### PR TITLE
Optional ark-transcript and merlin

### PR DESCRIPTION
**Pull request by davxy**
- Feature gate ark-transcript and merlin
- Simple transcript for tests

### CODE REVIEW

**Comment by burdges** [comment]
Is there a reason to keep merlin?

**Comment by davxy** [comment]
No not really, I added it just because is a popular implementation for FS.
But if you prefer I can remove it

**Comment by burdges** [comment]
I've no optinion, just curious.  I didn't make transcript traits around ArkTranscript because doing so adds complexity downstream.  I guess that's still the right choice, but never sure.  ;)

**Comment by swasilyev** [comment]
We decided not to use merlin. Also not a fan of extra features.

**Pull request closed without merging**
